# Pytorch Tensor Tutorial
Initializing tensors, math, indexing, reshaping
## Tensor Initialization

In [2]:
import torch

# create a tensor
device = "cuda" if torch.cuda.is_available() else "cpu" # if we have a GPU then use it

my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], # 2 rows and 3 columns
                         dtype=torch.float32, # float32 type
                         device=device, requires_grad=True) # default device = "cpu"
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


We can see the attributes of a tensor like below, which we have defined when initialiazation.

In [3]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

torch.float32
cpu
torch.Size([2, 3])
True


Other initialization methods:

In [15]:
x = torch.empty(size = (3, 3)) # random values
print(x)

tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])


In [10]:
x = torch.zeros((3, 3)) # zeros values
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [11]:
x = torch.rand((3, 3)) # random values in [0,1]
print(x)

tensor([[0.5978, 0.9819, 0.0438],
        [0.3936, 0.8372, 0.2535],
        [0.9933, 0.9542, 0.1583]])


In [12]:
x = torch.ones((3, 3)) # ones values
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [20]:
x = torch.eye(5, 5) # identity matrix
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [14]:
x = torch.arange(start=0, end=5, step=1) # range[0,5]
print(x)

tensor([0, 1, 2, 3, 4])


In [16]:
x = torch.linspace(start=0.1, end=1, steps=10) # equal cut into parts
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [17]:
x = torch.empty(size = (1, 5)).normal_(mean=0, std=1) # normal distribution
print(x)

tensor([[-0.1050,  0.6378,  0.9851,  0.5098,  0.5755]])


In [18]:
x = torch.empty(size = (1, 5)).uniform_(0, 1) # uniform distribution, same as torch.rand()
print(x)

tensor([[0.3263, 0.8763, 0.2628, 0.0903, 0.1561]])


In [19]:
x = torch.diag(torch.ones(3)) # diagonal matrix with ones values, same as torch.eye(3, 3)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


How to initialize and convert tensors to other types (int, float, double)

In [21]:
# create an int64 tensor
tensor = torch.arange(4)
# convert it into a boolean tensor
print(tensor.bool())
# convert to int16 tensor
print(tensor.short())
# convert to int64 tensor
print(tensor.long()) # important to use
# convert to float16 tensor
print(tensor.half())
# convert to float32 tensor
print(tensor.float()) # most often to use
# convert to float64 tensor
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)
